package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/andylokandy/prom-scopedb-adaptor/internal/scopedb"

	"github.com/prometheus/client_golang/prometheus"
	"github.com/prometheus/client_golang/prometheus/promhttp"
	"go.uber.org/zap"
)

var (
	samplesWrittenTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "samples_written_total",
			Help: "number of samples written into the backend",
		})
	writeRequestsTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "write_requests_total",
			Help: "number of hits to write endpoint",
		})
	writeErrorsTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "write_errors_total",
			Help: "number of errors generated by write endpoint",
		})
	readRequestsTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "read_requests_total",
			Help: "number of hits to read endpoint",
		})
	readErrorsTotal = prometheus.NewCounter(
		prometheus.CounterOpts{
			Name: "read_errors_total",
			Help: "number of errors generated by read endpoint",
		})
)

func init() {
	prometheus.MustRegister(samplesWrittenTotal)
	prometheus.MustRegister(writeRequestsTotal)
	prometheus.MustRegister(writeErrorsTotal)
	prometheus.MustRegister(readRequestsTotal)
	prometheus.MustRegister(readErrorsTotal)
}

// Update function signature to use ScopeDBAdapter
func read(adapter *scopedb.ScopeDBAdapter, w http.ResponseWriter, r *http.Request) error { // << CHANGED
	req, err := DecodeReadRequest(r.Body)
	if err != nil {
		return fmt.Errorf("DecodeReadRequest: %w", err)
	}

	// Call the adapter's ReadRequest method
	res, err := adapter.ReadRequest(r.Context(), req) // << CHANGED
	if err != nil {
		return fmt.Errorf("ReadRequest: %w", err) // Error message updated
	}

	w.Header().Set("Content-Type", "application/x-protobuf")
	w.Header().Set("Content-Encoding", "snappy")

	if err := EncodeReadResponse(res, w); err != nil {
		return fmt.Errorf("EncodeReadResponse: %w", err)
	}

	return nil
}

func main() {
	var httpAddr string
	// ScopeDB flags
	var scopeEndpoint string
	var scopeTable string
	var readIgnoreLabel string
	var readIgnoreHints bool
	var debug bool
	flag.StringVar(&httpAddr, "http", "9131", "listen on this [address:]port")
	flag.StringVar(&scopeEndpoint, "scopedb.endpoint", "http://localhost:6543", "ScopeDB endpoint URL")
	flag.StringVar(&scopeTable, "scopedb.table", "metrics.prometheus.samples", "ScopeDB target table (database.schema.table)")
	flag.StringVar(&readIgnoreLabel, "read.ignore-label", "remote=scopedb", "ignore this label=value pair in read requests")
	flag.BoolVar(&readIgnoreHints, "read.ignore-hints", true, "ignore step/range hints in read requests (ScopeDB implementation is basic)")
	flag.BoolVar(&debug, "debug", false, "print debug messages (including ScopeDB queries)")
	flag.Parse()

	if !strings.Contains(httpAddr, ":") {
		httpAddr = ":" + httpAddr
	}

	logger, err := zap.NewProduction()
	if err != nil {
		panic(err)
	}

	// Instantiate ScopeDB adapter
	adapter, err := scopedb.NewScopeDBAdapter(&scopedb.Config{
		Endpoint:        scopeEndpoint,
		Table:           scopeTable,
		ReadIgnoreLabel: readIgnoreLabel,
		ReadIgnoreHints: readIgnoreHints,
		Debug:           debug,
	})
	if err != nil {
		logger.Fatal("NewScopeDBAdapter", zap.Error(err))
	}

	http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(http.StatusNotFound)
		_, _ = io.WriteString(w, "prom-scopedb-adaptor")
		r.Body.Close()
	})

	http.Handle("/metrics", promhttp.Handler())

	http.HandleFunc("/write", func(w http.ResponseWriter, r *http.Request) {
		writeRequestsTotal.Inc()
		defer r.Body.Close()
		req, err := DecodeWriteRequest(r.Body)
		if err != nil {
			writeErrorsTotal.Inc()
			logger.Error("DecodeWriteRequest", zap.Error(err))
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
		// Use the adapter's WriteRequest
		if count, err := adapter.WriteRequest(r.Context(), req); err != nil { // << CHANGED
			writeErrorsTotal.Inc()
			logger.Error("WriteRequest", zap.Error(err)) // << Error message updated
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		} else if count > 0 {
			samplesWrittenTotal.Add(float64(count))
		}
	})

	http.HandleFunc("/read", func(w http.ResponseWriter, r *http.Request) {
		readRequestsTotal.Inc()
		defer r.Body.Close()
		// Pass the adapter to the read function
		if err := read(adapter, w, r); err != nil && !errors.Is(err, context.Canceled) { // << CHANGED
			readErrorsTotal.Inc()
			logger.Error("ReadRequest", zap.Error(err)) // << Error message updated
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}
	})

	logger.Info(
		"listening",
		zap.String("listen", httpAddr),
		zap.String("scopedb_endpoint", scopeEndpoint),
		zap.String("scopedb_table", scopeTable),
	)

	if err := http.ListenAndServe(httpAddr, nil); err != nil {
		logger.Fatal("ListenAndServe", zap.Error(err))
	}
}
